config/routes.rb
Rails.application.routes.draw do
  resources :bands
  get 'home/index'

  resources :medicine_intake_logs
  resources :doctor_notifications
  resources :user_vital_logs
  resources :in_patients
  resources :prescribed_medicines do
    get 'filtered', :on => :collection
  end
  resources :prescriptions
  resources :medicines
  resources :doctor_appointments
  resources :doctors do
    get 'login', :on => :collection
    post 'signin', :on => :collection
    get 'logout', :on => :collection
  end
  resources :users do
    get 'login', :on => :collection
    post 'signin', :on => :collection
    get 'logout', :on => :collection
  end
  get 'user_vital_summary', to: 'user_vital_summary#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to => 'home#index'
  #root to: 'stories#top'
  get 'stories',to: 'stories#top'
 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/band.rb
class Band < ApplicationRecord
end

app/models/doctor.rb
class Doctor < ApplicationRecord
end

app/models/doctor_appointment.rb
class DoctorAppointment < ApplicationRecord
  belongs_to :doctor
  belongs_to :user
end

app/models/doctor_notification.rb
class DoctorNotification < ApplicationRecord
  belongs_to :user
  belongs_to :doctor
end

app/models/in_patient.rb
class InPatient < ApplicationRecord
  belongs_to :user
  belongs_to :doctor
end

app/models/medicine.rb
class Medicine < ApplicationRecord
end

app/models/medicine_intake_log.rb
class MedicineIntakeLog < ApplicationRecord
  belongs_to :prescribed_medicine
  belongs_to :user
end

app/models/prescribed_medicine.rb
class PrescribedMedicine < ApplicationRecord
  belongs_to :medicine
  belongs_to :prescription
end

app/models/prescription.rb
class Prescription < ApplicationRecord
  belongs_to :user
  belongs_to :doctor
  has_many :prescribed_medicines
end

app/models/prime.rb
class Prime < ApplicationRecord
end

app/models/search.rb
class PagesController < ApplicationRecord
  belongs_to :user
  belongs_to :doctor
end


app/models/user.rb
class User < ApplicationRecord
  has_many :prescriptions
end

app/models/user_vital_log.rb
class UserVitalLog < ApplicationRecord
  belongs_to :user
end

app/models/user_vital_summary.rb
class UserVitalSummary
  include ActiveModel::Model
  attr_accessor :user_vital_log, :pressure_status, :sugar_status, :temperature_status, :pulse_status
  def attributes
    {'user_vital_log' => nil, 'pressure_status' => nil, 'sugar_status' => nil, 'temperature_status' => nil, 'pulse_status' => nil}
  end
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :set_band, only: %i[ show edit update destroy ]

  # GET /bands or /bands.json
  def index
    @bands = Band.all
  end

  # GET /bands/1 or /bands/1.json
  def show
  end

  # GET /bands/new
  def new
    @band = Band.new
  end

  # GET /bands/1/edit
  def edit
  end

  # POST /bands or /bands.json
  def create
    @band = Band.new(band_params)

    respond_to do |format|
      if @band.save
        format.html { redirect_to @band, notice: "Band was successfully created." }
        format.json { render :show, status: :created, location: @band }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @band.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bands/1 or /bands/1.json
  def update
    respond_to do |format|
      if @band.update(band_params)
        format.html { redirect_to @band, notice: "Band was successfully updated." }
        format.json { render :show, status: :ok, location: @band }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @band.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bands/1 or /bands/1.json
  def destroy
    @band.destroy
    respond_to do |format|
      format.html { redirect_to bands_url, notice: "Band was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_band
      @band = Band.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def band_params
      params.require(:band).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/in_patients_helper.rb
module InPatientsHelper
end

app/helpers/medicines_helper.rb
module MedicinesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bands/_form.html.erb
<%= form_with(model: band) do |form| %>
  <% if band.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(band.errors.count, "error") %> prohibited this band from being saved:</h2>

      <ul>
        <% band.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/bands/edit.html.erb
<h1>Editing Band</h1>

<%= render 'form', band: @band %>

<%= link_to 'Show', @band %> |
<%= link_to 'Back', bands_path %>

app/views/bands/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bands</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bands.each do |band| %>
      <tr>
        <td><%= band.name %></td>
        <td><%= link_to 'Show', band %></td>
        <td><%= link_to 'Edit', edit_band_path(band) %></td>
        <td><%= link_to 'Destroy', band, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Band', new_band_path %>

app/views/bands/new.html.erb
<h1>New Band</h1>

<%= render 'form', band: @band %>

<%= link_to 'Back', bands_path %>

app/views/bands/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @band.name %>
</p>

<%= link_to 'Edit', edit_band_path(@band) %> |
<%= link_to 'Back', bands_path %>